### ISSUE TITLE
DataRow.create_metadata does not work

### ISSUE THREAD

**Issue by jay-karimi** [Labelbox/labelbox-python#136] opened 2021-04-06 21:06 UTC
package version: `2.5.3`
example script:
```python
from labelbox import Client, DataRow, Dataset, Task
from uuid import uuid4

if __name__ == '__main__':
    client = Client()
    dataset: Dataset = client.get_dataset('ckn6amg8z0o9y0y853h3o6k8t')
    external_id = str(uuid4())
    print(external_id)
    task: Task = dataset.create_data_rows([{
        'row_data': 'https://i.ytimg.com/vi/SQJrYw1QvSQ/maxresdefault.jpg',
        'external_id': external_id,
    }])
    row: DataRow = dataset.data_row_for_external_id(external_id)
    row.create_metadata(meta_type='TEXT', meta_value='meeoowww')
```

This runs successfully. However, viewing the asset (programmatically & through the labelbox web UI) shows no metadata. This previously worked:
![Screen Shot 2021-04-06 at 2 06 18 PM](https://user-images.githubusercontent.com/54861081/113778511-4edf5800-96e1-11eb-8b1c-53c360afb73d.png)

**Comment by jay-karimi** [comment] 2021-04-06 21:12
After some investigating, this seems to be an edge case bug:
**GIVEN:** a dataset with integration enabled & 1 or more existing assets in the dataset with a bad `row_data` field such that `check integration status` fails the data access step
**WHEN:** you try to attach an asset to an existing asset or create a new asset and attach meta data to it
**THEN:** the newly added asset meta data is hidden from the UI and SDK until the existing assets with bad `row_data` fields are deleted

**Comment by msokoloff1** [comment] 2021-04-22 13:20
I tried reproducing this issue and was unable to. Also it looks like the text is attached in the abvoe screenshotWhat do you mean by `the newly added asset meta data is hidden from the UI and SDK`.

**Comment by msokoloff1** [comment] 2021-04-28 13:18
Closing this for now. Please reopen if you are still having this issue.

**Closed by msokoloff1** 2021-04-28 13:18 UTC
